matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      language: generic
      sudo: required
      dist: xenial
      language: node_js
      node_js: "12"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - yarn
script:
  - yarn build:electron --publish always
before_cache:
  - rm -rf $HOME/.cache/electron-builder

branches:
  only:
    - "release"